myWeb/urls.py
from django.contrib import admin
from django.conf.urls import include
from django.urls import path

urlpatterns = [
    path("", include('storyWeb.urls'))
]

storyWeb/urls.py
from django.urls import path
from . import views

app_name = "myweb"
#url for app
urlpatterns = [
    path('', views.homePage, name= 'homePage'),
    path('portofolio/', views.portofolio, name= 'portofolio')
]

storyWeb/models.py
from django.db import models

# Create your models here.

storyWeb/views.py
from django.shortcuts import render
# Create your views here.
def homePage(request):
    return render(request, 'Story3.html')

def portofolio(request):
    return render(request, 'story3_porto.html')

storyWeb/templates/Story3.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id= "home">
        <div id="homeText">
            <h1 id="Hi">Hi There!</h1>
            <p id="thanks">Thank you for visiting my web!</p>
            <p id="regards">regard - Ryo Axtonlie</p>
        </div>
    </div>

    <div id="aboutMe">
        <div id="aboutMeShapeText">
                <div class="square"></div>
                <div id="aboutMeText">
                        <h1>ABOUT ME</h1>
                        <p>I'm currently studying in Universitas Indonesia
                            , as third semester college student majoring 
                            Computer Science. I've been learning about editing 
                            and want to improve my UI/UX creation skills 
                            as well, so i'm participating in Faculty of 
                            Computer Science Executive Council of Student 
                            Media Bureau.  On my daily activity, other than 
                            studying, i liked to do photograhy with phones 
                            as an amateur photographer and listening to  
                            Country or Pop music.     
                        </p>
                </div>
        </div>
        <img src="{% static 'photo/aboutMePhoto.jpg' %}" alt="">
    </div>

    <div id="skills">
        <h1>SKILLS</h1>
        <div id="skillsLine1">
            <div id="java">
                <p>Java</p>
            </div>
            <div id="html5">
                <p>HTML 5</p>
            </div>
            <div id="css">
                <p>CSS</p>
            </div>
        </div>

        <div id="skillsLine2">
            <div id="illustrator">
                <p>illustrator</p>
            </div>
            <div id="photograph">
                <p>Photograph</p>
            </div>
        </div>
    </div>

    <div id="education">
        <img src="{% static 'photo/educationPhoto.png' %}" alt="">
        <div id="eduHistory">
            <h1>EDUCATION</h1>
            <div id="currentEdu">
                <h2>Universitas Indonesia, Bachelor
                    of Computer Science
                </h2>
                <p>August 2018 - Present</p>
            </div>
            <div id="pastEdu">
                <div id="sma">
                    <h2>SMAK 2 PENABUR Jakarta</h2>
                    <p>July 2015 - May 2018</p>
                </div>
                <div id="smp">
                    <h2>SMP Santo Yoseph</h2>
                    <p>July 2012 - May 2015</p>
                </div>
                <div id="sd">
                    <h2>SD Santo Yoseph</h2>
                    <p>July 2006 - May 2012</p>
                </div>
            </div>
        </div>
    </div>

    <div id="experience">
        <div id="experienceList">
            <h1>EXPERIENCE</h1>
            <div id="orgCommit">
                <div id="organization">
                    <h2>Organization</h2>
                    <div id="bemMedia">
                        <h3>Staff of Media Bureau at BEM
                            Fasilkom UI
                        </h3>
                        <p>Creating posters for media partner
                        and PIC of Boolean quarter magazine
                        </p>
                    </div>
                    <div id="kominfo">
                        <h3>Staff of Kominfo Department at KMBUI</h3>
                        <p>Contributes for creating holiday posters</p>
                    </div>
                </div>
                <div id="committee">
                    <h2>Committee</h2>
                    <div id="sea">
                        <h3>Staff of Software Engineering Academy
                            at Compfest 11
                        </h3>
                        <p>Managing schedule and preparing Academy
                            events
                        </p>
                    </div>
                    <div id="waisak">
                        <h3>Staff of Design at Waisak KMBUI 2019</h3>
                        <p>Creating posters for Waisak KMBUI 2019 posts</p>
                    </div>
                    <div id="toefl">
                        <h3>Staff of TOEFL Test at Educare Fasilkom UI 2019</h3>
                        <p>Organizing TOEFL Test participant</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

storyWeb/templates/base.html
{% load static %}

<!DOCTYPE html>
<html>
    <head>
        <meta charset = "UTF-8">
        <meta name= "viewport" content="width=device-width, initial-scale=1.0">
        <title>Ryo's Website</title>
        <link rel="stylesheet" href="{% static 'CSS_Story3.css' %}">
        <link rel="stylesheet" href="{% static 'bootstrap-4.3.1-dist/css/bootstrap.min.css' %}">
    </head>

    <body>
        <nav class="navbar fixed-top navbar-expand-xl navbar-dark">
            <a class="navbar-brand" href="{% url 'myweb:homePage' %}">HOME</a>
            <button class="navbar-toggler mt-2" type="button" data-toggle="collapse" data-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myweb:homePage' %}#aboutMe">ABOUT ME</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myweb:homePage' %}#skills">SKILLS</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myweb:homePage' %}#education">EDUCATION</a>
                </li>
                <li class="nav-item">
                  <a class="nav-link" href="{% url 'myweb:homePage' %}#experience">EXPERIENCE</a>
                </li>
                <li class="porto nav-item">
                        <a class="nav-link" href="{% url 'myweb:portofolio' %}">PORTOFOLIO</a>
                    </li>               
                <li class="nav-item">
                  <a class="nav-link" href="#connect">CONNECT</a>
                </li>
                <li class="divider"></li>
              </ul>
            </div>
          </nav> 

          {% block content %}
          {% endblock %}
          
          <footer id="connect">
            <div id="connectData">   
                <p>Connect With Me</p>             
                <div id="socmed">
                    <a id="fb" href="https://www.facebook.com/ryoaxton2000" target="_blank">
                        <img src="{% static 'logo/fb.svg' %}" alt="">
                    </a>
                    <a id="ig" href="https://www.instagram.com/ryo_axton" target="_blank">
                        <img src="{% static 'logo/ig.svg' %}" alt="">
                    </a>
                    <a id="linkedIn" href="https://www.linkedin.com/in/ryo-axtonlie" target="_blank">
                        <img src="{% static 'logo/linkedIn.svg' %}" alt="">
                    </a>
                </div>
            </div>
        </footer>

        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

    </body>
</html>

storyWeb/templates/story3_porto.html
{% extends "base.html" %}
{% load static %}

{% block content %}
    <div id="portoPhotography">
        <h1>Photography</h1>
        <p>*every picture is taken with smartphone and remain unedited</p>
        <div id="imgList">
            <img id="img1" src="{% static 'portofolio/img1.jpg' %}" alt="">
            <img id="img2" src="{% static 'portofolio/img2.jpg' %}" alt="">
            <img id="img3" src="{% static 'portofolio/img3.jpg' %}" alt="">
            <img id="img4" src="{% static 'portofolio/img4.jpg' %}" alt="">
            <img id="img5" src="{% static 'portofolio/img5.jpg' %}" alt="">
            <img id="img6" src="{% static 'portofolio/img6.jpg' %}" alt="">
            <img id="img7" src="{% static 'portofolio/img7.jpg' %}" alt="">
            <img id="img8" src="{% static 'portofolio/img8.jpg' %}" alt="">
            <img id="img9" src="{% static 'portofolio/img9.jpg' %}" alt="">
            <img id="img10" src="{% static 'portofolio/img10.jpg' %}" alt="">
            <img id="img11" src="{% static 'portofolio/img11.jpg' %}" alt="">
            <img id="img12" src="{% static 'portofolio/img12.jpg' %}" alt="">
            <img id="img13" src="{% static 'portofolio/img13.jpg' %}" alt="">
            <img id="img14" src="{% static 'portofolio/img14.jpg' %}" alt="">
            <img id="img15" src="{% static 'portofolio/img15.jpg' %}" alt="">
            <img id="img16" src="{% static 'portofolio/img16.jpg' %}" alt="">
        </div>
    </div>
{% endblock %}